## B-day Gift Hackerrank challenge

In [34]:
import numpy as np

#price on each ball
balls = np.array([1,1,2])
balls

array([1, 1, 2])

In [35]:
#number of balls
n_balls = len(balls)
n_balls

3

In [36]:
#find the possible coin flips
#rows (2**n_balls) represent the different number of possible coin flips
#columns (n_balls) represent number of balls
flip = np.zeros([2**n_balls,n_balls])

#0 represents tails, and 1 represent heads
#initial possibility is [0,0,0], which corresponds to [tails,tails,tails]
#for loop begins modifying the next possibility 
for row in range(1,2**n_balls):
    #copy the flips from previous possibility
    flip[row,:] = flip[row-1,:]
    #start from column 0 and progresses to column 2 
    for col in range(0,n_balls):
        #if column value is 0, change number to 1
        #and break loop to advance next row
        if flip[row,col] == 0:
            flip[row,col] = 1
            break
        elif flip[row,col]==1:
            flip[row,col] = 0
    
            
        
flip

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [37]:
balls_tile = np.tile(balls,(2**n_balls,1))
balls_tile

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [38]:
#calcuate the price of balls that have a coin flip of heads
price = np.multiply(flip,balls_tile)
price

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 0., 2.],
       [1., 0., 2.],
       [0., 1., 2.],
       [1., 1., 2.]])

In [39]:
#total price of each possibility
totalprice = np.sum(price,axis =1)
totalprice

array([0., 1., 1., 2., 2., 3., 3., 4.])

In [40]:
#average price from all possibilities
meanprice = np.sum(totalprice)/2**n_balls
meanprice

2.0

In [41]:
#simpler method to get the same answer
mean_price_simple = sum(balls)/2
mean_price_simple

2.0